[package]
name = "my_public_transport"
version = "0.1.0"
authors = ["Pascal Benchimol <pascal.benchimol@kisio.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
transit_model = "0.17"
typed_index_collection = "1"
chrono = "0.4"
log = "0.4"
