# adapted from :
# - newrelic basic setup https://docs.newrelic.com/docs/more-integrations/open-source-telemetry-integrations/opentelemetry/collector/opentelemetry-collector-basic/
# - new relic collector for host monitoring https://docs.newrelic.com/docs/more-integrations/open-source-telemetry-integrations/opentelemetry/collector/opentelemetry-collector-infra-hosts
# - prometheus receiver for opentelemetry https://github.com/open-telemetry/opentelemetry-collector-contrib/tree/main/receiver/prometheusreceiver

receivers:
  prometheus:
    config:
      scrape_configs:
        - job_name: "otel-collector"
          scrape_interval: 5s
          static_configs:
            - targets: ["LOKI_HTTP_ADDRESS"]

processors:
  memory_limiter:
    check_interval: 1s
    limit_mib: 1000
    spike_limit_mib: 200
  batch:
  cumulativetodelta:


exporters:
  otlp:
    # endpoint should include gRPC port number, e.g: /https://otlp.nr-data.net:4317
    # see https://docs.newrelic.com/docs/more-integrations/open-source-telemetry-integrations/opentelemetry/opentelemetry-setup#review-settings
    endpoint: ${NEWRELIC_ENDPOINT}
    headers:
      api-key: ${NEWRELIC_LICENSE_KEY}

service:
  pipelines:
    metrics:
      receivers: [prometheus]
      # NewRelic does not accept cumulative histogram (yet?) and that is what is produced by prometheus receiver
      # so we need to transform the cumulative histogram to a delta one
      # see https://docs.newrelic.com/docs/more-integrations/open-source-telemetry-integrations/opentelemetry/best-practices/opentelemetry-best-practices-metrics#otel-histogram
      processors: [batch, cumulativetodelta]
      exporters: [otlp]
