[package]
name = "loki_server"
version = "0.1.0"
authors = ["Pascal Benchimol <pascal.benchimol@kisio.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
# for navitia_proto
prost = "0.8"

# for chaos_proto which uses protobuf v2 extensions features, which are not supported by prost
# cf https://github.com/tokio-rs/prost/issues/100
protobuf = "2"

# Zmq lib with async interface
tmq = "0.3"
tokio = { version = "1", features = ["sync", "macros", "rt"] }
futures = { version = "0.3", default-features = false, features = ["alloc"] }

# RabbitMq lib
# !! We use the integration with tokio through tokio-amqp
# We should use version of lapin that tokio-amqp uses
lapin = "1.6"
tokio-amqp = "1"


launch = { path = "../launch"}
structopt = "0.3"
failure = "0.1"
serde = "1.0"
serde_json = "1.0"
relational_types = "2.0.0"

[build-dependencies]
prost-build = "0.8"
protobuf-codegen-pure = "2"
