[package]
name = "laxatips_server"
version = "0.1.0"
authors = ["Pascal Benchimol <pascal.benchimol@kisio.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
prost = "0.6"
zmq = "0.9"
laxatips = { path = "../"}
structopt = "0.3"
chrono = "0.4"
chrono-tz = "0.5"
failure = "0.1"
slog = "2.5"
slog-term = "2.4"
slog-scope = "4.1"
slog-stdlog = "4.0"
slog-async = "2.3"
slog-envlogger = "2.1"
serde = "1.0"
serde_json = "1.0"
# log = { version = "0.4", features = ["max_level_debug", "release_max_level_warn"] }

[build-dependencies]
prost-build = "0.6"