
start_stop_area = 'uri_of_start_stop_area'

end_stop_area = 'uri_of_end_stop_area'


# Departure datetime of the query, formatted like 20190628T163215
# If none is given, all queries will be made at 08:00:00 on the first
# valid day of the dataset
datetime = '20190628T163215'

# the given datetime is interpreted as
# a 'departure' or 'arrival' time
# defaults to "departure"

datetime_represent = 'departure'

# Which comparator to use for the request
# can be "basic" or "loads"
# defaults to "basic"

comparator_type = 'basic'


[launch_params]

# in which folder the input data is located
# REQUIRED
input_data_path = '/path/to/my/ntfs/folder'

# the format of the input files
# can be : 'ntfs' or 'gtfs'
# defaults to 'ntfs'

input_data_type = 'ntfs'

# path to the passengers loads file
# defaults to None

loads_data_path = '/path/to/passagenrs/loads/file'

# the input data may contains a transfer with no
# duration. In this case, we will use this value as the duration.
# defaults to '00:01:00', which means 1 minute

default_transfer_duration = '00:01:00'

[request_params]
leg_arrival_penalty = '00:02:00'
leg_walking_penalty = '00:02:00'
max_nb_of_legs = 10
max_journey_duration = '24:00:00'
too_late_threshold = '02:00:00'
real_time_level = 'base'
