[package]
name = "launch"
version = "0.1.0"
authors = ["Pascal Benchimol <pascal.benchimol@kisio.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
loki = { path = "../"}
serde = { version = "1.0", features = ["derive"] }
structopt = "0.3"
serde_json = "1.0"
slog = "2.5"
slog-term = "2.4"
slog-scope = "4.1"
slog-stdlog = "4.0"
slog-async = "2.3"
slog-envlogger = "2.1"

[dev-dependencies]
failure = "0.1"
env_logger = "0.9.0"
rstest = "0.11"

[features]
# enable the vehicle_loads feature on the loki lib
vehicle_loads = ["loki/vehicle_loads"]
