name: Dockers

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build dockers
      run: |
        build_dockers.sh -o ${{ secrets.OAUTH_TOKEN }}
    - name: Binarize
      run: docker run -v "$PWD":/storage -v /var/run/docker.sock:/var/run/docker.sock   mc_navitia/bina 
    - name: Launch dockers
      working-directory: ./mc_navitia
      run: |
        docker-compose up --detach
    - name: tests
      run: |
      http "http://localhost:9191/v1/coverage/auvergne-laxatips-loads/journeys?from=stop_area%3Astop_area%3A8739357&to=stop_area%3Astop_area%3A8775860&_override_scenario=distributed&datetime=20200505T080000&""