name: Dockers & Artemis

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    if: ${{ github.actor != 'dependabot[bot]' }}
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        submodules: recursive
    - name: Build dockers
      run: |
        ./build_dockers.sh -o ${{secrets.oauth_token}}
    - name: Binarize
      run: docker run --rm -v "$PWD":/storage -v /var/run/docker.sock:/var/run/docker.sock   navitia/mc_bina
    - name: Launch dockers
      working-directory: ./mc_navitia
      run: |
        docker-compose up --detach
    - name: install test depedencies
      run: sudo apt install -y httpie jq

    - name: Test corse loki
      run: |
        result=$( http GET 'http://127.0.0.1:9191/v1/coverage/corse/journeys?from=8.73421%3B41.91907&to=8.76055%3B41.92878&datetime=20200505T091505&_override_scenario=distributed&_use_pt_socket=True&' | jq .journeys[0].duration)
        test $result != null
    - name: Test corse kraken
      run: |
        result=$( http GET 'http://127.0.0.1:9191/v1/coverage/corse/journeys?from=8.73421%3B41.91907&to=8.76055%3B41.92878&datetime=20200505T091505&_override_scenario=distributed&' | jq .journeys[0].duration)
        test $result != null

    - name: Test transilien basic
      run: |
        result=$( http GET 'http://127.0.0.1:9191/v1/coverage/transilien/journeys?from=stop_area%3ADUA8775810&to=stop_area%3ADUA8739357&datetime=20210322T142346&_override_scenario=distributed&_use_pt_socket=True&' | jq .journeys[0].duration)
        test $result != null
    - name: Test transilien kraken
      run: |
        result=$( http GET 'http://127.0.0.1:9191/v1/coverage/transilien/journeys?from=stop_area%3ADUA8775810&to=stop_area%3ADUA8739357&datetime=20210322T142346&_override_scenario=distributed&' | jq .journeys[0].duration)
        test $result != null

    - name: Test idfm basic
      run: |
        result=$( http GET 'http://127.0.0.1:9191/v1/coverage/idfm/journeys?from=stop_area%3Astop_area%3A8775810&to=stop_area%3Astop_area%3A59033&datetime=20200505T080000&_override_scenario=distributed&_use_pt_socket=True&' | jq .journeys[0].duration)
        test $result != null
    - name: Test idfm kraken
      run: |
        result=$( http GET 'http://127.0.0.1:9191/v1/coverage/idfm/journeys?from=stop_area%3Astop_area%3A8775810&to=stop_area%3Astop_area%3A59033&datetime=20200505T080000&_override_scenario=distributed&' | jq .journeys[0].duration)
        test $result != null

    - name: logs
      working-directory: ./mc_navitia
      if: failure()
      run: |
        docker-compose logs

    - name: push docker images to dockerhub
      if: ${{ success() && github.event_name == 'push' && github.ref == 'refs/heads/master' }}
      run: |
        echo ${{ secrets.DOCKERHUB_PASSWORD }} | docker login -u ${{ secrets.DOCKERHUB_USERNAME }} --password-stdin
        docker push navitia/mc_bina
        docker push navitia/mc_loki
        docker push navitia/mc_jormun
        docker push navitia/mc_kraken
        docker logout

    - name: cleanup
      working-directory: ./mc_navitia
      if: always()
      run: |
        docker-compose down --rmi all -v

  artemis:
    if: ${{ github.event_name == 'push' && github.ref == 'refs/heads/master' }}
    runs-on: ubuntu-latest
    needs: build
    steps:
    # inspired by https://github.com/actions/virtual-environments/issues/709
    - name: Free up space
      run: |
        sudo apt clean
        rm --recursive --force /usr/share/dotnet/*
        rm --recursive --force "$AGENT_TOOLSDIRECTORY"

    - uses: actions/checkout@v2
      with:
        submodules: 'recursive'
    - uses: actions/setup-python@v2
      with:
        python-version: '3.7'

    # Checkout Artemis & submodules
    # Use custom Artemis for the moment
    # We discard test_idfm_11 (crash)
    - name: Checkout Artemis
      env:
        ARTEMIS_GITHUB_TOKEN: ${{secrets.oauth_token}}
      run: |
        mkdir -p ../artemis
        git clone https://$ARTEMIS_GITHUB_TOKEN@github.com/CanalTP/artemis.git --branch master ../artemis
        git clone https://$ARTEMIS_GITHUB_TOKEN@github.com/CanalTP/artemis_data.git --branch master ../artemis/artemis_data

    # Pull & build docker images
    - name: Build bina, Kraken, Jormun & Loki images
      run: |
        echo ${{ secrets.DOCKERHUB_PASSWORD }} | docker login -u ${{ secrets.DOCKERHUB_USERNAME }} --password-stdin
        docker pull navitia/mc_bina
        docker pull navitia/mc_kraken
        docker pull navitia/mc_jormun
        docker pull navitia/mc_loki
        cd ../artemis
        docker build -t artemis .

    # Copy artemis/data/{coverage}/fusio to ./loki/data/{coverage}/ntfs
    # Create dir for idfm references
    - name: Copy coverage data
      run: |
        rm -rf ./data/*
        mkdir -p ./data/idfm/ntfs
        cp -r -a ../artemis/artemis_data/idfm/fusio/. ./data/idfm/ntfs
        mkdir -p ./data/idfm/geopal
        cp -r -a ../artemis/artemis_data/idfm/geopal/. ./data/idfm/geopal
        mkdir -p ../artemis/artemis_references/TestIdfM

    # Run binarisation
    - name: Run Artemis binarisation
      run: |
        docker run --rm -v "$PWD":/storage -v /var/run/docker.sock:/var/run/docker.sock  navitia/mc_bina

    # we don't need the mc_bina container and image anymore
    - name: Clean unused docker images
      run: |
        docker rmi --force navitia/mc_bina
        docker rm --force navitia/mc_bina

    # the binarisation step put everything we need in ./mc_navitia,
    # so we can remove ./data and ../artemis/artemis_data/
    # so let's remove artemis_data
    - name: Clean unused data
      run: |
        rm -rf  ./data/
        rm -rf ../artemis/artemis_data/


    # Start dockers
    - name: Start dockers
      run: |
        docker-compose -f ./mc_navitia/docker-compose.yml up --detach

    # Run Tests with Kraken & create refs
    - name: Run Tests Kraken
      run: |
        cd ../artemis
        docker run  \
        --network host \
        -v $PWD:/usr/src/app  \
        -e ARTEMIS_LOG_LEVEL=INFO \
        -e ARTEMIS_USE_LOKI=False   \
        -e ARTEMIS_USE_ARTEMIS_NG=True   \
        -e ARTEMIS_URL_JORMUN=http://localhost:9191 \
        -e ARTEMIS_REFERENCE_FILE_PATH='artemis_references' \
        artemis py.test ./artemis/tests/idfm_test.py --skip_cities --skip_bina --create_ref --benchmark-json benchmark-kraken.json

    # Run Tests with Loki & compare with refs
    - name: Run Tests Loki
      continue-on-error: true
      run: |
        cd ../artemis
        docker run  \
        --network host \
        -v $PWD:/usr/src/app  \
        -e ARTEMIS_LOG_LEVEL=INFO \
        -e ARTEMIS_USE_LOKI=True   \
        -e ARTEMIS_USE_ARTEMIS_NG=True   \
        -e ARTEMIS_URL_JORMUN=http://localhost:9191 \
        -e ARTEMIS_REFERENCE_FILE_PATH='artemis_references' \
        artemis py.test ./artemis/tests/idfm_test.py --skip_cities --skip_bina --benchmark-json benchmark-loki.json

    # Stash modification to upload benchmark to gh-pages
    - name: Stash
      run: git stash

    - name: Compute Global benchmark for Artemis-Kraken
      run: |
          TOTAL_RUN=$(cat ../artemis/benchmark-kraken.json | jq '[.. | objects | .mean] | add' )
          OPS=$(echo "scale=10; 1.0 /  $TOTAL_RUN " | bc)
          STD_DEV=$(echo "scale=10; 0.1 /  $TOTAL_RUN " | bc)
          cat ../artemis/benchmark-kraken.json | jq '.benchmarks |= [{"group": "IdfM", "name": "artemis/global_test_", "fullname": "artemis/global_test_", "params": null, "param": null, "extra_info": {}, "stats": { "ops" : "'"$OPS"'", "mean" : "'"$TOTAL_RUN"'", "rounds" : 1, "stddev" : "'"$STD_DEV"'" }  }] + .' >> ../artemis/benchmark-kraken_edit.json

    - name: Compute Global benchmark for Artemis-Loki
      run: |
          TOTAL_RUN=$(cat ../artemis/benchmark-loki.json | jq '[.. | objects | .mean] | add' )
          OPS=$(echo "scale=10; 1.0 /  $TOTAL_RUN " | bc)
          STD_DEV=$(echo "scale=10; 0.1 /  $TOTAL_RUN " | bc)
          cat ../artemis/benchmark-loki.json | jq '.benchmarks |= [{"group": "IdfM", "name": "artemis/global_test_", "fullname": "artemis/global_test_", "params": null, "param": null, "extra_info": {}, "stats": { "ops" : "'"$OPS"'", "mean" : "'"$TOTAL_RUN"'", "rounds" : 1, "stddev" : "'"$STD_DEV"'" }  }] + .' >> ../artemis/benchmark-loki_edit.json

    - name: Store Kraken benchmark result
      uses: rhysd/github-action-benchmark@v1
      with:
        name: Kraken Benchmark
        tool: 'pytest'
        output-file-path: ../artemis/benchmark-kraken_edit.json
        benchmark-data-dir-path: './artemis-kraken'
        max-items-in-chart: 30
        github-token: ${{ secrets.oauth_token }}
        auto-push: true
        alert-threshold: '150%'
        comment-on-alert: true
        fail-on-alert: false
        alert-comment-cc-users: '@pbench,@AzHicham,@xlqian'

    - name: Store Loki benchmark result
      uses: rhysd/github-action-benchmark@v1
      with:
        name: Loki Benchmark
        tool: 'pytest'
        output-file-path: ../artemis/benchmark-loki_edit.json
        benchmark-data-dir-path: './artemis-loki'
        max-items-in-chart: 30
        github-token: ${{ secrets.oauth_token }}
        auto-push: true
        alert-threshold: '150%'
        comment-on-alert: true
        fail-on-alert: false
        alert-comment-cc-users: '@pbench,@AzHicham,@xlqian'

    - name: Copy artifacts & logs for archive
      run: |
          mkdir -p artemis
          cp -r -a ../artemis/output/ ./artemis/output

    - name: Archive Artemis artifacts (logs + ref)
      if: ${{ always() }}
      uses: actions/upload-artifact@v2
      with:
        name: logs-and-ref
        path: |
            ./artemis/output/**/*
