name: Dockers

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest
    steps:
    - name : Checkout
      uses: actions/checkout@v2
      with:
        submodules: recursive
    - name: Build dockers
      run: |
        ./build_dockers.sh -o ${{secrets.oauth_token}}
    - name: Binarize
      run: docker run -v "$PWD":/storage -v /var/run/docker.sock:/var/run/docker.sock   mc_navitia/bina 
    - name: Launch dockers
      working-directory: ./mc_navitia
      run: |
        docker-compose up --detach
    - name: install test depedencies
      run: sudo apt install -y httpie jq

    - name: Test corse loads
      run: |
        result=$( http 'http://localhost:9191/v1/coverage/corse-loki-loads/journeys?from=8.73421%3B41.91907&to=8.76055%3B41.92878&datetime=20200505T091505&_override_scenario=distributed&' | jq .journeys[0].duration)
        test $result != null
    - name: Test corse basic
      run: |
        result=$( http 'http://localhost:9191/v1/coverage/corse-loki-basic/journeys?from=8.73421%3B41.91907&to=8.76055%3B41.92878&datetime=20200505T091505&_override_scenario=distributed&' | jq .journeys[0].duration)
        test $result != null
    - name: Test corse kraken
      run: |
        result=$( http 'http://localhost:9191/v1/coverage/corse-kraken/journeys?from=8.73421%3B41.91907&to=8.76055%3B41.92878&datetime=20200505T091505&_override_scenario=distributed&' | jq .journeys[0].duration)
        test $result != null


    - name: Test transilien loads
      run: |
        result=$( http 'http://localhost:9191/v1/coverage/transilien-loki-loads/journeys?from=stop_area%3ADUA8775810&to=stop_area%3ADUA8739357&datetime=20210322T142346&_override_scenario=distributed&' | jq .journeys[0].duration)
        test $result != null
    - name: Test transilien basic
      run: |
        result=$( http 'http://localhost:9191/v1/coverage/transilien-loki-basic/journeys?from=stop_area%3ADUA8775810&to=stop_area%3ADUA8739357&datetime=20210322T142346&_override_scenario=distributed&' | jq .journeys[0].duration)
        test $result != null
    - name: Test transilien kraken
      run: |
        result=$( http 'http://localhost:9191/v1/coverage/transilien-kraken/journeys?from=stop_area%3ADUA8775810&to=stop_area%3ADUA8739357&datetime=20210322T142346&_override_scenario=distributed&' | jq .journeys[0].duration)
        test $result != null



    - name: Test idfm loads
      run: |
        result=$( http 'http://localhost:9191/v1/coverage/idfm-loki-loads/journeys?from=stop_area%3Astop_area%3A8775810&to=stop_area%3Astop_area%3A59033&datetime=20200505T080000&_override_scenario=distributed&' | jq .journeys[0].duration)
        test $result != null
    - name: Test idfm basic
      run: |
        result=$( http 'http://localhost:9191/v1/coverage/idfm-loki-loads/journeys?from=stop_area%3Astop_area%3A8775810&to=stop_area%3Astop_area%3A59033&datetime=20200505T080000&_override_scenario=distributed& | jq .journeys[0].duration)
        test $result != null
    - name: Test idfm kraken
      run: |
        result=$( http 'http://localhost:9191/v1/coverage/idfm-loki-loads/journeys?from=stop_area%3Astop_area%3A8775810&to=stop_area%3Astop_area%3A59033&datetime=20200505T080000&_override_scenario=distributed&' | jq .journeys[0].duration)
        test $result != null