name: Dockers

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Build dockers
      run: |
        ./build_dockers.sh -o ${{secrets.oauth_token}}
    - name: Binarize
      run: docker run -v "$PWD":/storage -v /var/run/docker.sock:/var/run/docker.sock   mc_navitia/bina 
    - name: Launch dockers
      working-directory: ./mc_navitia
      run: |
        docker-compose up --detach
    - name: install test depedencies
      run: sudo apt install -y httpie jq
    - name: Test auvergne loads
      run: |
        result=$( http 'http://127.0.0.1:9191/v1/coverage/auvergne-loki-loads/journeys?from=stop_area:stop_area:8739357&to=stop_area:stop_area:8775860&_override_scenario=distributed&datetime=20200505T080000&' | jq .error )
        test $result = null
    - name: Test auvergne basic
      run: |
        result=$( http 'http://127.0.0.1:9191/v1/coverage/auvergne-loki-basic/journeys?from=stop_area:stop_area:8739357&to=stop_area:stop_area:8775860&_override_scenario=distributed&datetime=20200505T080000&' | jq .error )
        test $result = null
    - name: Test auvergne kraken
      run: |
        result=$( http 'http://127.0.0.1:9191/v1/coverage/auvergne-kraken/journeys?from=stop_area:stop_area:8739357&to=stop_area:stop_area:8775860&_override_scenario=distributed&datetime=20200505T080000&' | jq .error )
        test $result = null

    - name: Test idfm loads
      run: |
        result=$( http 'http://127.0.0.1:9191/v1/coverage/idfm-loki-loads/journeys?from=stop_area:stop_area:8739357&to=stop_area:stop_area:8775860&_override_scenario=distributed&datetime=20200505T080000&' | jq .error )
        test $result = null
    - name: Test idfm basic
      run: |
        result=$( http 'http://127.0.0.1:9191/v1/coverage/idfm-loki-basic/journeys?from=stop_area:stop_area:8739357&to=stop_area:stop_area:8775860&_override_scenario=distributed&datetime=20200505T080000&' | jq .error )
        test $result = null
    - name: Test idfm kraken
      run: |
        result=$( http 'http://127.0.0.1:9191/v1/coverage/idfm-kraken/journeys?from=stop_area:stop_area:8739357&to=stop_area:stop_area:8775860&_override_scenario=distributed&datetime=20200505T080000&' | jq .error )
        test $result = null
