name: Sonar

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  CARGO_TERM_COLOR: always

jobs:
  clippy:
    name: Analyzing code with Clippy
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        submodules: 'recursive'
    - name: Install libzmq
      run: |
        sudo apt install libzmq3-dev
    - name: Install Rust stable
      uses: actions-rs/toolchain@v1
      with:
          toolchain: stable
          profile: minimal
          components: clippy
    - name: Run cargo clippy
      run: cargo clippy --workspace --all-features --message-format=json -- --warn clippy::pedantic > clippy.json
    - name: Install 'cargo-sonar'
      run: cargo install cargo-sonar
    - name: Convert into Sonar compatible format
      run: cargo-sonar --clippy
    - name: Run sonar-scanner
      uses: SonarSource/sonarcloud-github-action@master
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
      with:
        args: >
          -Dsonar.projectKey=CanalTP_loki
          -Dsonar.projectName=loki
          -Dsonar.sources=.
          -Dsonar.sourceEncoding=UTF-8
          -Dsonar.rust.clippy.reportPaths=sonar.json
          -Dsonar.organization=canaltp
          -Dsonar.verbose=true
