name: Sonar

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  CARGO_TERM_COLOR: always

jobs:
  sonar:
    if: ${{ github.actor != 'dependabot[bot]' }}
    name: Analyzing code with Clippy
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
      with:
        submodules: 'recursive'
    - name: Install dependencies
      run: |
        sudo apt install libzmq3-dev lld
    - name: Install Rust stable
      uses: actions-rs/toolchain@v1
      with:
          toolchain: stable
          profile: minimal
          components: clippy
    - name: Run cargo clippy
      run: cargo clippy --workspace --all-features --message-format=json -- --warn clippy::pedantic > clippy.json
    - name: Install 'cargo-sonar'
      run: cargo install cargo-sonar --version 0.9.0 --locked
    - name: Convert into Sonar compatible format
      run: cargo-sonar --features clippy --clippy-path clippy.json
    - name: Run sonar-scanner
      uses: SonarSource/sonarcloud-github-action@master
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
      with:
        args: >
          -Dsonar.projectKey=Hove_loki
          -Dsonar.projectName=loki
          -Dsonar.sources=.
          -Dsonar.sourceEncoding=UTF-8
          -Dsonar.externalIssuesReportPaths=sonar.json
          -Dsonar.organization=hove-io
          -Dsonar.verbose=true
