name: Build and test

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        submodules: 'recursive'
    - name: Install libzmq
      run: |
        sudo apt install libzmq3-dev
    - name: Check compilation
      run: cargo check --workspace --verbose
    - name: Run tests in debug mode
      run: cargo test --workspace
    - name: Run tests in debug mode with vehicle_loads feature
      run: cargo test --workspace --features="loki_stop_areas/vehicle_loads"
    - name: Run tests in release mode
      run: cargo test --release --workspace

  pre-commit:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        submodules: 'recursive'
    - uses: actions-rs/toolchain@v1
      with:
        toolchain: stable
        override: true
    - name: install dependencies
      run: |
        sudo apt update
        sudo apt install -y python3 python3-pip git
        pip install pre-commit
    - name: Pre-commit
      run: |
        pre-commit install --install-hooks
        pre-commit run --all --show-diff-on-failure
